// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaytsuokbbuhrfruewqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFheXRzdW9rYmJ1aHJmcnVld3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDcxNjAsImV4cCI6MjA1ODg4MzE2MH0.Ry6lQHnmtP3Ik26A_8i41OMBupgn0yciZ5udHt2-dTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);