name: Test Scrapers

on:
  pull_request:
    paths:
      - 'scrapers/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd scrapers
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper tests
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
      run: |
        cd scrapers
        python src/test_scraper.py